name: Hello Testing
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build:
    name: Build and Run
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build Code
        run: pwd && whoami && ls -l && make
      - name: Nominal Run
        run: ./hello
